<?php
defined('BASEPATH') OR exit('No direct script access allowed');

/*
| -------------------------------------------------------------------
| CURRENCIES CONFIGURATIONS
| -------------------------------------------------------------------
| This file contains an array of currencies to be used in cuur helper.
|
| Access the array in $this->config->item('currencies)
*/

$config = array(
    'currencies' => array(
        //     Code      Name  
        array("INR",    "Indian rupee"),
        array("USD",    "US dollar"),
        array("CAD",    "Canadian dollar"),
        array("MXN",    "Mexican peso"),
        array("EUR",    "EU euro"),
        array("AED",    "UAE dirham"),
        array("AFA",    "Afghanistan afghani"),
        array("ALL",    "Albanian lek"),
        array("AMD",    "Armenian dram"),
        array("ANG",    "Netherlands Antillian guilder"),
        array("AOR",    "Angolan kwanza reajustado"),
        array("ARS",    "Argentine peso"),
        array("AUD",    "Australian dollar"),
        array("AWG",    "Aruban guilder"),
        array("AZN",    "Azerbaijanian new manat"),
        array("BBD",    "Barbados dollar"),
        array("BDT",    "Bangladeshi taka"),
        array("BGN",    "Bulgarian lev"),
        array("BHD",    "Bahraini dinar"),
        array("BIF",    "Burundi franc"),
        array("BMD",    "Bermudian dollar"),
        array("BND",    "Brunei dollar"),
        array("BOB",    "Bolivian boliviano"),
        array("BRL",    "Brazilian real"),
        array("BSD",    "Bahamian dollar"),
        array("BTN",    "Bhutan ngultrum"),
        array("BWP",    "Botswana pula"),
        array("BYN",    "Belarusian ruble"),
        array("BZD",    "Belize dollar"),
        array("CAD",    "Canadian dollar"),
        array("CDF",    "Congolese franc"),
        array("CHF",    "Swiss franc"),
        array("CLP",    "Chilean peso"),
        array("CNY",    "Chinese yuan renminbi"),
        array("COP",    "Colombian peso"),
        array("CRC",    "Costa Rican colon"),
        array("CUP",    "Cuban peso"),
        array("CVE",    "Cape Verde escudo"),
        array("CZK",    "Czech koruna"),
        array("DJF",    "Djibouti franc"),
        array("DKK",    "Danish krone"),
        array("DOP",    "Dominican peso"),
        array("DZD",    "Algerian dinar"),
        array("EEK",    "Estonian kroon"),
        array("EGP",    "Egyptian pound"),
        array("ERN",    "Eritrean nakfa"),
        array("ETB",    "Ethiopian birr"),
        array("FJD",    "Fiji dollar"),
        array("FKP",    "Falkland Islands pound"),
        array("GBP",    "British pound"),
        array("GEL",    "Georgian lari"),
        array("GHS",    "Ghanaian new cedi"),
        array("GIP",    "Gibraltar pound"),
        array("GMD",    "Gambian dalasi"),
        array("GNF",    "Guinean franc"),
        array("GTQ",    "Guatemalan quetzal"),
        array("GYD",    "Guyana dollar"),
        array("HKD",    "Hong Kong SAR dollar"),
        array("HNL",    "Honduran lempira"),
        array("HRK",    "Croatian kuna"),
        array("HTG",    "Haitian gourde"),
        array("HUF",    "Hungarian forint"),
        array("IDR",    "Indonesian rupiah"),
        array("ILS",    "Israeli new shekel"),
        array("IQD",    "Iraqi dinar"),
        array("IRR",    "Iranian rial"),
        array("ISK",    "Icelandic krona"),
        array("JMD",    "Jamaican dollar"),
        array("JOD",    "Jordanian dinar"),
        array("JPY",    "Japanese yen"),
        array("KES",    "Kenyan shilling"),
        array("KGS",    "Kyrgyz som"),
        array("KHR",    "Cambodian riel"),
        array("KMF",    "Comoros franc"),
        array("KPW",    "North Korean won"),
        array("KRW",    "South Korean won"),
        array("KWD",    "Kuwaiti dinar"),
        array("KYD",    "Cayman Islands dollar"),
        array("KZT",    "Kazakh tenge"),
        array("LAK",    "Lao kip"),
        array("LBP",    "Lebanese pound"),
        array("LKR",    "Sri Lanka rupee"),
        array("LRD",    "Liberian dollar"),
        array("LSL",    "Lesotho loti"),
        array("LTL",    "Lithuanian litas"),
        array("LVL",    "Latvian lats"),
        array("LYD",    "Libyan dinar"),
        array("MAD",    "Moroccan dirham"),
        array("MDL",    "Moldovan leu"),
        array("MGA",    "Malagasy ariary"),
        array("MKD",    "Macedonian denar"),
        array("MMK",    "Myanmar kyat"),
        array("MNT",    "Mongolian tugrik"),
        array("MOP",    "Macao SAR pataca"),
        array("MRO",    "Mauritanian ouguiya"),
        array("MUR",    "Mauritius rupee"),
        array("MVR",    "Maldivian rufiyaa"),
        array("MWK",    "Malawi kwacha"),
        array("MYR",    "Malaysian ringgit"),
        array("MZN",    "Mozambique new metical"),
        array("NAD",    "Namibian dollar"),
        array("NGN",    "Nigerian naira"),
        array("NIO",    "Nicaraguan cordoba oro"),
        array("NOK",    "Norwegian krone"),
        array("NPR",    "Nepalese rupee"),
        array("NZD",    "New Zealand dollar"),
        array("OMR",    "Omani rial"),
        array("PAB",    "Panamanian balboa"),
        array("PEN",    "Peruvian nuevo sol"),
        array("PGK",    "Papua New Guinea kina"),
        array("PHP",    "Philippine peso"),
        array("PKR",    "Pakistani rupee"),
        array("PLN",    "Polish zloty"),
        array("PYG",    "Paraguayan guarani"),
        array("QAR",    "Qatari rial"),
        array("RON",    "Romanian new leu"),
        array("RSD",    "Serbian dinar"),
        array("RUB",    "Russian ruble"),
        array("RWF",    "Rwandan franc"),
        array("SAR",    "Saudi riyal"),
        array("SBD",    "Solomon Islands dollar"),
        array("SCR",    "Seychelles rupee"),
        array("SDG",    "Sudanese pound"),
        array("SEK",    "Swedish krona"),
        array("SGD",    "Singapore dollar"),
        array("SHP",    "Saint Helena pound"),
        array("SLL",    "Sierra Leone leone"),
        array("SOS",    "Somali shilling"),
        array("SRD",    "Suriname dollar"),
        array("STD",    "Sao Tome and Principe dobra"),
        array("SVC",    "El Salvador colon"),
        array("SYP",    "Syrian pound"),
        array("SZL",    "Swaziland lilangeni"),
        array("THB",    "Thai baht"),
        array("TJS",    "Tajik somoni"),
        array("TMT",    "Turkmen new manat"),
        array("TND",    "Tunisian dinar"),
        array("TOP",    "Tongan pa'anga"),
        array("TRY",    "Turkish lira"),
        array("TTD",    "Trinidad and Tobago dollar"),
        array("TWD",    "Taiwan New dollar"),
        array("TZS",    "Tanzanian shilling"),
        array("UAH",    "Ukrainian hryvnia"),
        array("UGX",    "Uganda new shilling"),
        array("UYU",    "Uruguayan peso uruguayo"),
        array("UZS",    "Uzbekistani sum"),
        array("VEF",    "Venezuelan bolivar fuerte"),
        array("VND",    "Vietnamese dong"),
        array("VUV",    "Vanuatu vatu"),
        array("WST",    "Samoan tala"),
        array("XAF",    "CFA franc BEAC"),
        array("XAG",    "Silver (ounce)"),
        array("XAU",    "Gold (ounce)"),
        array("XCD",    "East Caribbean dollar"),
        array("XDR",    "IMF special drawing right"),
        array("XFO",    "Gold franc"),
        array("XFU",    "UIC franc"),
        array("XOF",    "CFA franc BCEAO"),
        array("XPD",    "Palladium (ounce)"),
        array("XPF",    "CFP franc"),
        array("XPT",    "Platinum (ounce)"),
        array("YER",    "Yemeni rial"),
        array("ZAR",    "South African rand"),
        array("ZMK",    "Zambian kwacha"),
        array("ZWL",    "Zimbabwe dollar")
    )
);

?>